import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

const poppins = Poppins({
  subsets: ["latin", "latin-ext"], // latin-ext для підтримки більшої кількості символів
  display: "swap",
  variable: "--font-poppins", // Назва нашої CSS змінної
  weight: ["300", "400", "500", "600", "700", "800"], // Завантажуємо різні товщини
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="uk" suppressHydrationWarning>
      <body
        className={cn(
          "min-h-screen bg-background font-sans antialiased",
          poppins.variable // 4. Додаємо змінну шрифту до body
        )}
      >
        {children}
      </body>
    </html>
  );
}
